const INDUSTRY_DATA = [
  {"n":"Blue Collar","id":"rec9wGSGqjwW1eZ9R"},
  {"n":"Blue Collar-A/V Installer","id":"recFHPj5oZXrGqxwX"},
  {"n":"Blue Collar-Auto Body","id":"recBSiabgRU6GoX25"},
  {"n":"Blue Collar-Cleaners","id":"recMVZZ4wXR6E5Uww"},
  {"n":"Blue Collar-Construction","id":"recO4WfeqNS6y9tJ1"},
  {"n":"Blue Collar-Electrician","id":"rec4tJUBGnPZtXXaD"},
  {"n":"Blue Collar-Entertainment","id":"recVvBGRG1ZFnJz73"},
  {"n":"Blue Collar-Farm","id":"recG7oUp43odmnjbY"},
  {"n":"Blue Collar-Nursery","id":"recKIAnl5LGNdhGAc"},
  {"n":"Blue Collar-Online","id":"rec9k0k5UJ35j81KL"},
  {"n":"Blue Collar-Plumbing","id":"recQPvfjdowZZczW6"},
  {"n":"Blue Collar-Product","id":"recrsZasVQTXEYp0g"},
  {"n":"Blue Collar-Retail","id":"reck1bUAXbYVo3TWR"},
  {"n":"Blue Collar-Services","id":"rec9vkdWsOzgD5tbz"},
  {"n":"Blue Collar-Towing","id":"recag8zx9hA5G4D6j"},
  {"n":"Blue Collar-Transportation","id":"recS3lsAejFKMayda"},
  {"n":"Blue Collar-Wholesale","id":"rec0sVlSGhJai9rA2"},
  {"n":"Brewery","id":"recueDkgs9hBGJ9Zs"},
  {"n":"Builder","id":"recIoizP6pDSzgC5T"},
  {"n":"Church","id":"recB3zz0kzxkkOi0Z"},
  {"n":"E-Commerce","id":"recuywd22wsohr4sm"},
  {"n":"HOA","id":"recRY3qIJqzZUB1km"},
  {"n":"HotWorx","id":"rec4JAk5ulHf5y774"},
  {"n":"Hotel","id":"rec41iKK9wt8QLzhO"},
  {"n":"Investment PS","id":"recOLCN8wRPTCbiek"},
  {"n":"Manufacturing","id":"rec96Nqn6Oo78MDoO"},
  {"n":"NBC","id":"recxn9kcUqp3r49Lo"},
  {"n":"Non Profit","id":"recenqwYhNR7FQ3is"},
  {"n":"Non profit","id":"recouqwrJCVsZsY8h"},
  {"n":"Pawn Shop","id":"recSYGjejRdOTgC5m"},
  {"n":"Real Estate","id":"recRZARQIpESLsyiu"},
  {"n":"Restaurant","id":"recWRu81MkLAMuaGb"},
  {"n":"Retail","id":"rect83cMiNZlX9PBW"},
  {"n":"Service","id":"reczTai5muB9iLWPg"},
  {"n":"Service-Catering","id":"recUUKa5XnMpcaYP3"},
  {"n":"Service-Music Studio","id":"recBgSbPs0zZBTBuU"},
  {"n":"White Collar-Attorney","id":"reckymqUQsptI9El8"},
  {"n":"White Collar-Consultant","id":"rec5tX9wcvqTioqI7"},
  {"n":"White Collar-Consulting","id":"recZKkHBAfXwhuC32"},
  {"n":"White Collar-Dental Lab","id":"reccQEtFY4WLUc6zc"},
  {"n":"White Collar-Dentist","id":"recsCo7I83feIlSCF"},
  {"n":"White Collar-Doctor","id":"rec7RezlZvavM6gzm"},
  {"n":"White Collar-Engineer","id":"recVZtpLRwonh1RkQ"},
  {"n":"White Collar-Financial","id":"rectPbePzDAVLa8z6"},
  {"n":"White Collar-Financial Advisor","id":"recQoAKGF0Q55uKwn"},
  {"n":"White Collar-Insurance","id":"recEueQ6Rpc3NsSTK"},
  {"n":"White Collar-Investments","id":"recB2r40yBDgJkDG6"},
  {"n":"White Collar-Marketing","id":"recfU06vpqxgIDlTg"},
  {"n":"White Collar-Medical","id":"rec1a4CVMU3oU9gNl"},
  {"n":"White Collar-Medical Billing","id":"recSs7ubTmLeq5iBY"},
  {"n":"White Collar-Publishing","id":"recLXT4J41vRsRWCa"},
  {"n":"White Collar-Real Estate","id":"reclYcIyNcuGJikjE"},
  {"n":"White Collar-Sales","id":"recQqmHQIQYVotJhg"},
  {"n":"White Collar-Tech","id":"recozNuPIdlk7CvPQ"},
  {"n":"White Collar-Therapists","id":"reccGYLVaApVPhliD"},
  {"n":"White Collar-Vet","id":"rec3lu3JH5oTsX7kP"},
  {"n":"Wholesale","id":"rec60Pq9i0RRy3BIU"},
];